[package]
name = "ffsim"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "ffsim"
crate-type = ["cdylib"]

[dependencies]
rayon = "1.11"
blas = "0.23"
ndarray = { version = "0.15", features = ["rayon"] }
blas-src = { version = "0.10" }
numpy = "0.27"
pyo3 = { version = "0.27", features = [
    "extension-module",
    "num-complex",
    "abi3-py310",
] }
num-integer = "0.1"

[target.'cfg(target_os = "linux")'.dependencies]
blas-src = { version = "0.10", features = ["openblas"] }
openblas-src = { version = "0.10", features = ["system"] }
